.defaults: &use_defaults
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      #- ${CI_PROJECT_DIR}/.m2/repository
      - ~/.m2/repository
  before_script:
    # Check defined variables
    - printenv
    - echo "---------"
    - if [ ! "${APP_PATH}" ]; then echo "APP_PATH variable not defined!"; exit -1; fi
    - if [ ! "${GFT_LIBS_GET_CMD}" ]; then echo "You must include '.gft-libs.yml' before use this template!"; exit -1; fi
    - eval "${GFT_LIBS_GET_CMD}"
    - exports="$(${GFT_LIB_COMMON} printEnvMappedVarsExports)";
    - eval "${exports}"
    - ${GFT_LIB_COMMON} validateVars HOST_EXAMPLE
    - ${GFT_LIB_COMMON} verifyDeps mvn
    - printenv
    - echo "---------"
    - cd ${CI_PROJECT_DIR}/${APP_PATH}
  artifacts:
    paths:
      - ${APP_PATH}/target/**/*
    expire_in: 6 hour

  tags:
    - devops-runner-wsl

# Maven Build template
.mvn_build:
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} clean install

# Maven Sonar template
.mvn_sonar:
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} sonar:sonar

# Maven Nexus template
.mvn_nexus:
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} package

# Maven Deploy template
.mvn_deploy:
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} deploy