include:
  - local: .git-libs.yml

# GCP Run template
.gcp-template:
  before_script:
    - eval "${GFT_LIBS_GET_CMD}"
    - ${GFT_LIB_COMMON} map-vars    
    - ${GFT_LIB_COMMON} validateVars GOOGLE_APPLICATION_CREDENTIALS
    - ${GFT_LIB_COMMON} verifyDeps gcloud
