# Maven Run template
.mvn_run:
  #image: maven:latest
  variables:
    #MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
    MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=~/.m2/repository"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      #- ${CI_PROJECT_DIR}/.m2/repository
      - ~/.m2/repository
  before_script:
    # Check defined variables
    - if [ ! "${APP_PATH}" ]; then echo "APP_PATH variable not defined!"; exit -1; fi
    - if [ ! "${MAVEN_CMD}" ]; then echo "MAVEN_CMD variable not defined!"; exit -1; fi
    - cd ${CI_PROJECT_DIR}/${APP_PATH}
  script:
    mvn ${MAVEN_OPTS} ${MAVEN_CMD}
  artifacts:
    paths:
      - ${APP_PATH}/target/**/*
    expire_in: 6 hour