# Maven Run template
.mvn_run:
  image: maven:latest
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  variables:
    MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  before_script:
    # Check defined variables
    - if [ ! "${APP_PATH}" ]; then echo "APP_PATH variable not defined!"; exit -1; fi
    - cd ${APP_PATH}    
  artifacts:
    paths:
      - ${APP_PATH}/**/*
    expire_in: 6 hour