#######################################
# GFT libraries for .gitlab-ci.yml #
#
# Usage: Refer to README.md
#
#######################################

variables:
  GFT_LIBS_REPO: "devops-br/gitlab-gft-libs"
  GFT_LIBS_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@git.gft.com/${GFT_LIBS_REPO}.git"
  GFT_LIBS_DIR: "/tmp/${CI_PIPELINE_ID}"
  GFT_LIBS_GET_CMD: "test -f ${GFT_LIBS_DIR} || rm -rf ${GFT_LIBS_DIR}; git clone ${GFT_LIBS_URL} ${GFT_LIBS_DIR}; chmod +x /tmp/${CI_PIPELINE_ID}/libs/*.sh"
  GFT_LIBS_CONVERT_VARS: "exports=$$(${GFT_LIB_COMMON} printEnvMappedVarsExports); eval \"$${exports}\""

  ########## LIB CATALOG ############
  GFT_LIB_GCP: "/tmp/${CI_PIPELINE_ID}/libs/gcp.sh"
  GFT_LIB_COMMON: "/tmp/${CI_PIPELINE_ID}/libs/common.sh"
  GFT_LIB_UTILS: "/tmp/${CI_PIPELINE_ID}/libs/utils.sh"
  ###################################

.gft-libs:

  before_script:
    - |
      set_e_enabled=${-//[^x]/}
      [ $set_e_enabled ] || set +e
      echo "Downloading GFT libs..."
      eval "${GFT_LIBS_GET_CMD}"
      echo "GFT libs are available now!"
      echo "****************************************************"
      echo "Available libraries:"
      export | grep -o -e ' GFT_LIB_[_A-Z0-9]*' | sed 's/GFT_LIB_//'
      echo ""
      echo "Import using: import_gft_libs <LIB1> <LIB2> <LIBN>"
      echo "****************************************************"
      function import_gft_libs {
        while [ "$1" ]; do
          lib="${1}"
          lib_var="GFT_LIB_${1}"
          lib_file="${!lib_var}"
          # Check if lib exists
          if [ ! -f "${lib_file}" ]; then
            echo "GFT Library '${lib}' not found!"
            exit -1
          fi
          echo "Importing GFT Library: ${lib}..."
          source ${lib_file}
          shift
        done
      }      
      [ $set_e_enabled ] || set -e
    
