# Maven Run template
.mvn_run:
  #image: maven:latest
  variables:
    #MAVEN_OPTS: "--batch-mode -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
    MAVEN_CMD: "clean install"
    MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      #- ${CI_PROJECT_DIR}/.m2/repository
      - ~/.m2/repository
  before_script:
    # Check defined variables
    - printenv
    - echo "---------"
    - if [ ! "${APP_PATH}" ]; then echo "APP_PATH variable not defined!"; exit -1; fi
    - if [ ! "${GFT_LIBS_GET_CMD}" ]; then echo "You must include '.gft-libs.yml' before use this template!"; exit -1; fi
    - eval "${GFT_LIBS_GET_CMD}"
    - exports="$(${GFT_LIB_COMMON} printEnvMappedVarsExports)";
    - eval "${exports}"
    - ${GFT_LIB_COMMON} validateVars EXAMPLE
    - ${GFT_LIB_COMMON} verifyDeps mvn
    - printenv
    - echo "---------"
    - cd ${CI_PROJECT_DIR}/${APP_PATH}
  script:
    mvn ${MAVEN_OPTS} ${MAVEN_CMD}
  artifacts:
    paths:
      - ${APP_PATH}/target/**/*
    expire_in: 6 hour

  tags:
    - devops-runner-wsl