#######################################
# GITLAB libraries for .gitlab-ci.yml #
#
# Usage: Refer to README.md
#
#######################################

variables:
  GITLAB_LIBS_DIR: "/tmp/${CI_PIPELINE_ID}"
  GITLAB_LIBS_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@$(echo ${CI_PROJECT_URL} | cut -d'/' -f3)/${GITLAB_LIBS_REPO}.git"
  
  ########## LIB CATALOG ############
  GITLAB_LIB_UTILS: "/tmp/${CI_PIPELINE_ID}/libs/utils/main.sh"  
  GITLAB_LIB_GCP: "/tmp/${CI_PIPELINE_ID}/libs/gcp/main.sh"  
  GITLAB_LIB_GITSYNC: "/tmp/${CI_PIPELINE_ID}/libs/gitsync/main.sh"  
  ########## LIB COMMANDS ############
  #GITLAB_LIBS_CMD_IMPORT: "test -d ${GITLAB_LIBS_DIR} && rm -rf ${GITLAB_LIBS_DIR}; git clone ${GITLAB_LIBS_URL} ${GITLAB_LIBS_DIR}; find /tmp/${CI_PIPELINE_ID}/libs -name '*.sh' -exec chmod +x {} \\;; shopt -s expand_aliases; source ${GITLAB_LIBS_DIR}/libs/common.sh"

  GITLAB_LIBS_CMD_IMPORT: "if [ ! -d ${GITLAB_LIBS_DIR} ]; then echo "Clonning GitLab Libs..."; git clone ${GITLAB_LIBS_URL} ${GITLAB_LIBS_DIR}; else echo "Pulling GitLab Libs..."; git -C ${GITLAB_LIBS_DIR} pull; fi; find ${GITLAB_LIBS_DIR}/libs -name '*.sh' -exec chmod +x {} \\;; shopt -s expand_aliases; source ${GITLAB_LIBS_DIR}/libs/common.sh"
  ###################################

# Common lib template
.gitlab-common-template:
  before_script:
    - | 
      # .gitlab-common-template

      # Check and import gitlab-lib
      if [ ! "${GITLAB_LIBS_CMD_IMPORT}" ]; then echo "You must include '.gitlab-libs.yml' before use this template!"; exit -1; fi
      eval "${GITLAB_LIBS_CMD_IMPORT}"

      # Convert environment variables
      convertEnvVars ${GITLAB_LIBS_BRANCHES_DEFINITION}
