# Base template
.base-template:
  before_script:
    - | 
      # .base-template

      # Import DevOps Libs and convert environment variables
      source ${CI_PROJECT_DIR}/scripts/devops-libs.sh
      do.import git
      do.git.convertEnvVars ${CI_COMMIT_REF_NAME} ${DEVOPS_LIBS_BRANCHES_DEFINITION}
