# Base lib template
.base-template:
  before_script:
    - | 
      # .base-template

      # Import base libs and convert environment variables
      source ${CI_PROJECT_DIR}/scripts/gitlab-libs.sh
      convertEnvVars ${CI_COMMIT_REF_NAME} ${GITLAB_LIBS_BRANCHES_DEFINITION}
