# GCP Run template
.gcp-template:
  before_script:
    - | 
      # .gcp-template before_script

      # Import base libs and convert environment variables
      source ${CI_PROJECT_DIR}/scripts/gitlab-libs.sh      
      convertEnvVars ${CI_COMMIT_REF_NAME} ${GITLAB_LIBS_BRANCHES_DEFINITION}

      # Validate required vars and dependencies
      validateVars GCLOUD_CREDENTIAL GOOGLE_APPLICATION_CREDENTIALS      

      # Import GCP lib
      importLibs gcp

      # Install credential and set SA as active
      echo "${GCLOUD_CREDENTIAL}" > ${GOOGLE_APPLICATION_CREDENTIALS}

      # Activate the Service Account from credential
      gcplib.useSA ${GOOGLE_APPLICATION_CREDENTIALS}

  after_script:
    - | 
      # .gcp-template after_script
     
      set -x
      source ${CI_PROJECT_DIR}/scripts/gitlab-libs.sh offline

      # Reimport as after script process is other than before_script/script
      importLibs gcp

      # Revoke service account
      gcplib.revokeSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Delete installed credential
      rm -f ${GOOGLE_APPLICATION_CREDENTIALS}
