# GCP Run template
.gcp-template:
  before_script:
    - | 
      # .gcp-template before_script      

      # Check and import gitlab-lib
      if [ ! "${GITLAB_LIBS_CMD_IMPORT}" ]; then echo "You must include '.gitlab-libs.yml' before use this template!"; exit -1; fi
      eval "${GITLAB_LIBS_CMD_IMPORT}"

      # Convert environment variables
      convertEnvVars ${CI_COMMIT_REF_NAME} ${GITLAB_LIBS_BRANCHES_DEFINITION}

      # Import GCP lib
      importLibs GCP

      # Validate required vars and dependencies
      validateVars GCLOUD_CREDENTIAL GOOGLE_APPLICATION_CREDENTIALS
      verifyDeps gcloud

      # Install credential and set SA as active
      echo "${GCLOUD_CREDENTIAL}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      gcplib useSA ${GOOGLE_APPLICATION_CREDENTIALS}

  after_script:
    - |
      # .gcp-template after_script
      
      # Reimport as after script process is other than before_script/script
      importLibs GCP 

      # Revoke service account
      gcplib revokeSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Delete installed credential
      rm -f ${GOOGLE_APPLICATION_CREDENTIALS}
