# GCP Run template
.gcp-template:
  before_script:
    - |      
      # Disable script call ouput in case if enabled
      set_e_enabled=${-//[^x]/}; [ ${set_e_enabled} ] || set +e

      # Check and import gft-lib
      if [ ! "${GFT_LIBS_GET_CMD}" ]; then echo "You must include '.gft-libs.yml' before use this template!"; exit -1; fi
      eval "${GFT_LIBS_GET_CMD}"

      # Convert environment variables
      eval "${GFT_LIBS_CONVERT_VARS}"

      # Import GCP lib
      source ${GFT_LIB_GCP}      

      # Validate required vars and dependencies
      validateVars GCLOUD_CREDENTIAL GOOGLE_APPLICATION_CREDENTIALS
      verifyDeps gcloud

      # Install credential
      echo "${GCLOUD_CREDENTIAL}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      useSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Re-enable script call ouput in case was enabled
      [ ${set_e_enabled} ] || set -e

  after_script:
    - |    
      # Disable script call ouput in case if enabled
      set_e_enabled=${-//[^x]/}; [ ${set_e_enabled} ] || set +e

      # Revoke service account    
      ${GFT_LIB_GCP} revokeSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Delete installed credential
      rm -f ${GOOGLE_APPLICATION_CREDENTIALS}

      # Re-enable script call ouput in case was enabled
      [ ${set_e_enabled} ] || set -e
