# Maven Run template
.mvn-template:
  image: maven:latest
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
  before_script:
    - if [ ! "${GFT_LIBS_GET_CMD}" ]; then echo "You must include '.gft-libs.yml' before use this template!"; exit -1; fi
    - eval "${GFT_LIBS_GET_CMD}"
    - eval "${GFT_LIBS_ENV_VAR}"      
    # Get Variable related to the branch name
    - cd ${APP_PATH}
    - pwd
  artifacts:
    paths:
      - ${APP_PATH}/target/**/*
    expire_in: 6 hour