include:
  - local: '/.gft-libs.yml'

stages:
  - Build
  - Sonar
  - Nexus
  - Deploy
  
############## Default definitions ##############
.defaults: &use_defaults
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"
  cache:
    key: ${CI_JOB_NAME}
    paths:
      #- ${CI_PROJECT_DIR}/.m2/repository
      - ~/.m2/repository
  before_script:
    # Check defined variables
    - if [ ! "${APP_PATH}" ]; then echo "APP_PATH variable not defined!"; exit -1; fi
    - if [ ! "${GFT_LIBS_GET_CMD}" ]; then echo "You must include '.gft-libs.yml' before use this template!"; exit -1; fi
    - exports="$(${GFT_LIB_COMMON} printEnvMappedVarsExports)";
    - eval "${exports}"
    - ${GFT_LIB_COMMON} verifyDeps mvn
    - cd ${CI_PROJECT_DIR}/${APP_PATH}
  after_script:
    - echo "after script!"
  artifacts:
    paths:
      - ${APP_PATH}/target/**/*
    expire_in: 6 hour
  tags:
    - devops-runner-wsl

############## Maven Build template ##############
.mvn_build:
  stage: Build
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} clean install

############## Maven Sonar template ##############
.mvn_sonar:
  stage: Sonar
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} sonar:sonar

############## Maven Nexus template ##############
.mvn_nexus:
  stage: Nexus
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} package

############## Maven Deploy template ##############
.mvn_deploy:
  stage: Deploy
  <<: *use_defaults
  script:
    mvn ${MAVEN_OPTS} deploy