#!/bin/bash
CURRENT_LIB_DIR=$(dirname ${BASH_SOURCE[0]})
CURRENT_LIB_PATH=$(echo $(cd ${CURRENT_LIB_DIR} >/dev/null 2>&1 && pwd))
CURRENT_LIB_NAME=$(echo ${CURRENT_LIB_PATH} | awk -F / '{print $NF}')

# Include main code
source "${CURRENT_LIB_DIR}/main.sh"

# Include the footer
eval "${footLibScript}"
if [ $(basename ${0}) == $(basename ${BASH_SOURCE[0]}) ]; then 
    getArgs "function &@args" "${@}"
    ${function} "${args[@]}"
fi