# GCP Run template
.gcp-template:
  before_script:
    - |    
      # .gcp-template before_script
      # Disable script call ouput in case if enabled
      set_e_enabled=${-//[^x]/}; [ ${set_e_enabled} ] || set +e

      # Check and import gitlab-lib
      if [ ! "${GITLAB_LIBS_GET_CMD}" ]; then echo "You must include '.gitlab-libs.yml' before use this template!"; exit -1; fi
      eval "${GITLAB_LIBS_GET_CMD}"

      # Convert environment variables
      eval "${GITLAB_LIBS_CONVERT_VARS}"

      # Import GCP lib
      source ${GITLAB_LIB_GCP}      

      # Validate required vars and dependencies
      validateVars GCLOUD_CREDENTIAL GOOGLE_APPLICATION_CREDENTIALS
      verifyDeps gcloud

      # Install credential
      echo "${GCLOUD_CREDENTIAL}" > ${GOOGLE_APPLICATION_CREDENTIALS}
      gcplib.useSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Re-enable script call ouput in case was enabled
      [ ${set_e_enabled} ] || set -e

  after_script:
    - |
      # .gcp-template after_script
      # Disable script call ouput in case if enabled
      set_e_enabled=${-//[^x]/}; [ ${set_e_enabled} ] || set +e

      # Revoke service account    
      ${GITLAB_LIB_GCP} gcplib.revokeSA ${GOOGLE_APPLICATION_CREDENTIALS}

      # Delete installed credential
      rm -f ${GOOGLE_APPLICATION_CREDENTIALS}

      # Re-enable script call ouput in case was enabled
      [ ${set_e_enabled} ] || set -e
